
site_name: DIVE-DSA
site_url: https://github.io/BryonLewis/dive-dsa
site_description: Documentation for DIVE-DSA
site_author: Kitware

repo_url: https://github.com/BryonLewis/dive-dsa

theme:
  name: material
  highlightjs: true
  logo: images/General/Kitware-Mark.png
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

extra_css: [extra.css]

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kitware/dive
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kitware/viame-web
    - icon: fontawesome/brands/discourse
      link: https://discourse.kitware.com/c/viame-dive/17
  analytics:
    provider: google
    property: UA-6042509-43

nav:
  - User Guide:
    - Home: index.md
    - Web Version: Web-Version.md
    - Annotation Quickstart: Annotation-QuickStart.md
    - Technology Details:
      - Video Processing: VideoConversion.md
      - S3 Import: S3Import.md
    - User Interface Guide:
      - Introduction: Annotation-User-Interface-Overview.md
      - Navigation and Editing Bar: UI-Navigation-Editing-Bar.md
      - Annotation Window: UI-Annotation-View.md
      - Type List: UI-Type-List.md
      - Track List: UI-Track-List.md
      - Timeline: UI-Timeline.md
      - Attributes:
        - Attributes: UI-Attributes.md
        - Attribute Filtering: UI-AttributeFiltering.md
        - Attribute Timeline: UI-AttributeTimeline.md
        - Attribute Swimlane: UI-AttributeSwimlanes.md
        - Attribute Rendering: UI-AttributeRendering.md
      - Group Manager: UI-Group-Manager.md    
      - Dataset Info: UI-DatasetInfo.md
    - Configuration:
      - UI Configuration: UI-Configuration.md
      - UI Settings: UI-Settings.md
      - UI Actions: UI-Actions.md
      - UI Timeline Settings: UI-TimelineSettings.md
      - Configuration JSON: UI-ConfigurationJSON.md
    - Keyboard Shortcut Reference: Mouse-Keyboard-Shortcuts.md
    - Screenshots: Screenshots.md
    - Support: Support.md
  - Data Formats: DataFormats.md
  - Administrator Guide:
    - Running with Docker Compose: Deployment-Docker-Compose.md
    - REST API Specification: https://viame.kitware.com/api/v1
  - Support: Support.md
